#!/usr/bin/env node

// Launcher for the portable clone-website skill generated by
// scripts/sync-skills.mjs. It installs the bundled, version-matched cloner
// runtime once in a shared cache, then runs it against the current repository.
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SKILL_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CACHE_ROOT = process.env.CLONER_RUNTIME_CACHE
  ? resolve(process.env.CLONER_RUNTIME_CACHE)
  : join(homedir(), '.skills-manager', 'runtime-cache', 'clone-website');

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd,
    env: options.env ?? process.env,
    stdio: 'inherit',
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(`${command} exited with status ${result.status ?? 'unknown'}`);
  }
}

function bundledVersion() {
  const runtimeRoot = join(SKILL_ROOT, 'runtime');
  const versions = readdirSync(runtimeRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
  if (versions.length !== 1) throw new Error(`Expected exactly one bundled runtime in ${runtimeRoot}; found ${versions.length}.`);
  return versions[0];
}

function hashDirectory(directory) {
  const hash = createHash('sha256');
  const visit = (current, relative = '') => {
    for (const entry of readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const entryRelative = join(relative, entry.name);
      const entryPath = join(current, entry.name);
      if (entry.isDirectory()) visit(entryPath, entryRelative);
      else if (entry.isFile()) {
        hash.update(entryRelative);
        hash.update(readFileSync(entryPath));
      }
    }
  };
  visit(directory);
  return hash.digest('hex');
}

function cacheReady(ready, version, bundleHash) {
  try {
    const state = JSON.parse(readFileSync(ready, 'utf8'));
    return state.version === version && state.bundleHash === bundleHash;
  } catch {
    return false;
  }
}

function installRuntime({ version, bundle, bundleHash, cache }) {
  const ready = join(cache, '.ready.json');
  if (cacheReady(ready, version, bundleHash)) return;
  mkdirSync(CACHE_ROOT, { recursive: true });
  const lock = join(CACHE_ROOT, `.${version}.install-lock`);
  try {
    mkdirSync(lock);
  } catch (error) {
    if (error?.code === 'EEXIST') {
      throw new Error(`Cloner runtime ${version} installation is already running. Retry after it finishes.`);
    }
    throw error;
  }

  let stagingRoot;
  try {
    if (cacheReady(ready, version, bundleHash)) return;
    if (existsSync(cache)) rmSync(cache, { recursive: true, force: true });
    stagingRoot = mkdtempSync(join(CACHE_ROOT, `.${version}.staging-`));
    const staging = join(stagingRoot, version);
    cpSync(bundle, staging, { recursive: true });

    console.error(`Installing shared cloner runtime ${version} once...`);
    const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
    run(npm, ['ci', '--omit=dev', '--no-audit', '--no-fund'], { cwd: staging });

    const browser = spawnSync(
      process.execPath,
      [join(staging, 'node_modules', 'playwright', 'cli.js'), 'install', 'chromium'],
      { cwd: staging, env: process.env, stdio: 'inherit' },
    );
    const browserInstalled = browser.status === 0;
    if (!browserInstalled) {
      console.error('Chromium installation failed; cloner will try an installed Chrome browser.');
    }

    writeFileSync(
      join(staging, '.ready.json'),
      `${JSON.stringify({ version, bundleHash, browserInstalled }, null, 2)}\n`,
    );
    renameSync(staging, cache);
  } finally {
    if (stagingRoot) rmSync(stagingRoot, { recursive: true, force: true });
    rmSync(lock, { recursive: true, force: true });
  }
}

try {
  const nodeMajor = Number.parseInt(process.versions.node, 10);
  if (nodeMajor < 24) throw new Error(`Node.js 24 or newer is required; found ${process.versions.node}.`);
  const version = bundledVersion();
  const bundle = join(SKILL_ROOT, 'runtime', version);
  const bundleHash = hashDirectory(bundle);
  const cache = join(CACHE_ROOT, version);
  installRuntime({ version, bundle, bundleHash, cache });
  run(process.execPath, [join(cache, 'cli.mjs'), ...process.argv.slice(2)], {
    cwd: process.cwd(),
    env: { ...process.env, CLONER_ENGINE_SHA256: bundleHash },
  });
} catch (error) {
  console.error(`cloner launcher: ${error.message}`);
  process.exitCode = 1;
}
